// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsA-Trgi35g1w_JvcVMzUkBg0OkdlmT0U',
    appId: '1:349661507174:web:3b593e7b5e1996cab5c7a7',
    messagingSenderId: '349661507174',
    projectId: 'campus-connect-5e124',
    authDomain: 'campus-connect-5e124.firebaseapp.com',
    storageBucket: 'campus-connect-5e124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBu9qp8mi9H2rb_GFbt8OLuBlSn7PYD4',
    appId: '1:349661507174:android:6e0686f6679763b3b5c7a7',
    messagingSenderId: '349661507174',
    projectId: 'campus-connect-5e124',
    storageBucket: 'campus-connect-5e124.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5XW5DY-u4iBjotk5brFfod7TA0equy7M',
    appId: '1:349661507174:ios:5ffbe270e8f1b220b5c7a7',
    messagingSenderId: '349661507174',
    projectId: 'campus-connect-5e124',
    storageBucket: 'campus-connect-5e124.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5XW5DY-u4iBjotk5brFfod7TA0equy7M',
    appId: '1:349661507174:ios:5ffbe270e8f1b220b5c7a7',
    messagingSenderId: '349661507174',
    projectId: 'campus-connect-5e124',
    storageBucket: 'campus-connect-5e124.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsA-Trgi35g1w_JvcVMzUkBg0OkdlmT0U',
    appId: '1:349661507174:web:f4be259bcd5e3116b5c7a7',
    messagingSenderId: '349661507174',
    projectId: 'campus-connect-5e124',
    authDomain: 'campus-connect-5e124.firebaseapp.com',
    storageBucket: 'campus-connect-5e124.firebasestorage.app',
  );
}
